### ISSUE TITLE
Signup link is broken!

### ISSUE THREAD

**Issue by queirozfcom** [hightouch67/hightouch67.github.io#4]
The "Signup up on steemit.com" link on https://d.tube/#!/login is **broken**. It points to an old address: https://steemit.com/pick_account which doesn't exist anymore.

It should probably take users to https://signup.steemit.com/.

**Comment by skzap** [comment]
That was fixed on the day you created the issue :1st_place_medal: 

All good now, also SteemIt fixed it on their end by redirecting the old link to the new one.
