### ISSUE TITLE
Home page is blank in Seamonkey

### ISSUE THREAD

**Issue by Botster** [hightouch67/hightouch67.github.io#8]
This is not regarding the About page, but it was difficult determining the best place to report this.

The Home page, https://d.tube/ , loads fine in Epiphany and Firefox but Seamonkey v2.46 chokes on it.

The Javascript console says:
> 13:42:06.193 SyntaxError: missing = in const declaration19dc5a53d5860a33ba782b146e2a90263acd13978.js:17:1430259
> 13:42:06.193 ReferenceError: Meteor is not defined d.tube:13:1
> <anonymous>d.tube:13

Page source is:
<!DOCTYPE html>
<html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <link rel="stylesheet" type="text/css" class="__meteor-css__" href="./DTube_files/e54e3616ca58dbcadf79e681fd00d30beb7ca51c.css">
  <link rel="stylesheet" type="text/css" class="__meteor-css__" href="./DTube_files/dc7d3e881715b2630248433368d29d16ada51480.css">
  <link rel="stylesheet" type="text/css" class="__meteor-css__" href="./DTube_files/bea6f9c25b32ccc151a670990a2bdb4c4644bde0.css">
  <link rel="shortcut icon" type="image/png" href="./DTube_files/images/dtubefavicon.png">
  <title>DTube</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
  <script type="text/javascript">__meteor_runtime_config__ = JSON.parse(decodeURIComponent("%7B%22meteorRelease%22%3A%22METEOR%401.4.4.1%22%2C%22meteorEnv%22%3A%7B%22NODE_ENV%22%3A%22production%22%2C%22TEST_METADATA%22%3A%22%7B%7D%22%7D%2C%22PUBLIC_SETTINGS%22%3A%7B%7D%2C%22ROOT_URL%22%3A%22http%3A%2F%2Flocalhost%3A3000%2F%22%2C%22ROOT_URL_PATH_PREFIX%22%3A%22%22%2C%22appId%22%3A%22150zjr3301zki1vu3if5%22%2C%22autoupdateVersion%22%3A%22f99492306a9c2e8b74ec8d57b6be22b8eb19f240%22%2C%22autoupdateVersionRefreshable%22%3A%22e86b152ee079afa62b62b6d5106ea59d50331e9d%22%2C%22autoupdateVersionCordova%22%3A%22none%22%7D"));</script>
  <script type="text/javascript" src="./DTube_files/9dc5a53d5860a33ba782b146e2a90263acd13978.js"></script>
  <script type="text/javascript">Meteor.disconnect();</script>
</body></html>

**Comment by skzap** [comment]
This issue should be long in the production repository. But ok. My palemoon also doesn't load DTube. Probably some weird javascript syntax in our app not being parsed correctly by your browser javascript engine.

I recommend using a modern browser for now. Probably we should display something on the screen like 'Your browser doesn't support DTube, please upgrade to XXX' though when this case happens.

**Comment by Botster** [comment]
I found that 17:1430259 pointed to:
`if(this.clients)for(const e of this.clients)e.terminate();`

Seamonkey actually is a modern browser. It uses the same engine as Firefox, Gecko. Unfortunately for me, v2.46 is still using the Firefox 49.0 engine - which does not support the 'for...of' loop.

Yep, time to upgrade. Issue closed.
